# Generated by Django 5.2 on 2025-04-29 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=266)),
                ('is_recurring', models.CharField(choices=[('NO', 'No'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NO', max_length=10)),
                ('recurring_end_date', models.DateField(blank=True, null=True)),
                ('spent_by', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking'), ('PAYAPP', 'Payment App'), ('WALLET', 'Digital Wallet'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('transaction_category', models.CharField(choices=[('OFFLINE_MARKET', 'Offline Market'), ('ECOMMERCE', 'E-Commerce'), ('QUICK_COMMERCE', 'Quick Commerce'), ('MALL', 'Shopping Mall'), ('UTILITY', 'Utility Payment'), ('SUBSCRIPTION', 'Subscription'), ('RESTAURANT', 'Restaurant'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_expense_limit', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
