# Generated by Django 5.1.1 on 2025-04-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spent_by',
            field=models.CharField(max_length=50),
        ),
    ]
