# Generated by Django 5.1.1 on 2025-04-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenselimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.CharField(choices=[('NO', 'No'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NO', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
