# Generated by Django 5.1.6 on 2025-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_is_recurring_expense_recurring_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='spent_by',
            field=models.CharField(choices=[('Self', 'Self'), ('Dad', 'Dad'), ('Mom', 'Mom'), ('Sister', 'Sister'), ('Brother', 'Brother')], default='Self', max_length=10),
        ),
    ]
