# Generated by Django 5.1.1 on 2025-01-26 07:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finassist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueryLog',
            new_name='Chat',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='query',
            new_name='message',
        ),
    ]
