# Generated by Django 5.1.7 on 2025-04-28 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('SOLO', 'Solo Account'), ('MULTI', 'Multi-User Account')], default='SOLO', max_length=5)),
                ('profile_type', models.CharField(choices=[('OWNER', 'Account Owner'), ('MEMBER', 'Family Member')], default='OWNER', max_length=6)),
                ('relationship', models.CharField(blank=True, help_text='Relationship to account owner', max_length=50, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
